{
    'name': 'New Payroll',
    'version': '1.0',
    'author': 'Simon Temesgen', 
    'summary': 'Custom payroll module',
    'description': 'Manage payroll calculations.',
    'category': 'Human Resources',
    'depends': ['hr'],
    'data': [
        'views/payroll_views.xml',
        'views/payroll_templates.xml',
        'views/employee_portal_views.xml',
        'views/hr_contract_views.xml',
        'views/payroll_compliance_views.xml',
        'views/report_payslip_templates.xml',
        'security/employee_portal_security.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'report/payroll_report.xml',
        'data/payroll_data.xml',
    ],
    'installable': True,
    'application': True,
}